from __future__ import annotations

from sophons.documents.base import Document
from sophons.models.chat import AsyncChatModel
from sophons.models.messages import Message
from sophons.rag.splitters.interface import TextSplitter
from sophons.rag.splitters.recursive import RecursiveTextSplitter


_CONTEXT_PROMPT = """\
<document>
{document}
</document>

Here is the chunk we want to situate within the whole document:
<chunk>
{chunk}
</chunk>

Give a short succinct context (one or two sentences) that situates this chunk \
within the overall document, for the purpose of improving search retrieval. \
Answer only with the context and nothing else."""


class ContextualTextSplitter:
    """
    Enriches each chunk with document-level context generated by an LLM.

    Inspired by Anthropic's contextual retrieval technique: the LLM reads the
    full document alongside each chunk and generates a short context sentence
    that is prepended to the chunk before it is embedded.  This ensures that
    isolated chunks carry enough context to be retrieved accurately.

    Because the full document is included in every prompt, use a model with
    prompt caching (e.g. Claude) to avoid re-billing the document prefix on
    each chunk call.

    Args:
        model:        Async chat model used to generate context sentences.
        base_splitter: Splitter used to produce the raw chunks before
                       enrichment.  Defaults to ``RecursiveTextSplitter``.

    Usage::

        splitter = ContextualTextSplitter(model=my_model)
        chunks = splitter.split(Document(content=long_text, id="doc-1"))
    """

    def __init__(
        self,
        model: AsyncChatModel,
        base_splitter: TextSplitter | None = None,
    ) -> None:
        self._model = model
        self._base = base_splitter or RecursiveTextSplitter()

    def split(self, document: Document) -> list[Document]:
        raise NotImplementedError(
            "ContextualTextSplitter.split() is sync but requires an async model. "
            "Use split_async() instead."
        )

    async def split_async(self, document: Document) -> list[Document]:
        """Split and enrich chunks with LLM-generated context."""
        raw_chunks = self._base.split(document)
        enriched: list[Document] = []
        for chunk in raw_chunks:
            context = await self._generate_context(
                document=document.content,
                chunk=chunk.content,
            )
            enriched.append(
                Document(
                    content=f"{context}\n\n{chunk.content}",
                    metadata={**chunk.metadata, "has_context": True},
                    id=chunk.id,
                )
            )
        return enriched

    async def _generate_context(self, document: str, chunk: str) -> str:
        prompt = _CONTEXT_PROMPT.format(document=document, chunk=chunk)
        response = await self._model.invoke(
            [Message(role="user", content=prompt)]
        )
        return response.content.strip()
